influxdb:
  container_name: influxdb
  image: influxdb:latest
  environment:
    - INFLUXDB_DB=benchmark
    - INFLUXDB_ADMIN_USER=user
    - INFLUXDB_ADMIN_PASSWORD=password
  ports:
    - "8087:8086"
  volumes:
    - /mnt/data/influx/data:/var/lib/influxdb2
