influxql:
  container_name: influxql
  image: influxdb:1.8
  environment:
    - INFLUXDB_DB=benchmark
    - INFLUXDB_ADMIN_USER=user
    - INFLUXDB_ADMIN_PASSWORD=password
  ports:
    - "8087:8086"
  volumes:
    - /mnt/data/influxql/data:/var/lib/influxdb