timescaledb-single:
  container_name: timescaledb-single
  image: timescale/timescaledb:latest-pg14   
  environment:
    POSTGRES_PASSWORD: postgres
  ports:
    - "5432:5432"
  volumes:
    - /mnt/data/timescale/single-data:/var/lib/postgresql/data